apiVersion: v1
kind: Service
metadata:
  labels:
    app: craft
  name: craft
spec:
  ports:
  - name: caft-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: craft
  type: ClusterIP
status:
  loadBalancer: {}
